# Generated by Django 2.2.14 on 2021-05-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vegitable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('disc', models.TextField()),
                ('price', models.FloatField(default=0)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
