# Generated by Django 2.2.14 on 2021-05-26 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210522_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='ordered_on',
            field=models.DateField(default=datetime.datetime(2021, 5, 26, 6, 56, 0, 341017, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='posted_on',
            field=models.DateField(default=datetime.datetime(2021, 5, 26, 6, 56, 0, 341017, tzinfo=utc)),
        ),
    ]
